development:
  adapter: async
  #adapter: mysql2
  #url: 127.0.0.1
 
test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: Rails_MySQL_production
                                                                                 