# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000 


# mysqlconnect Setting
MySQLConnect: &mysqlconnect
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000  
  encoding: utf8
  username: <%= ENV["CONNECT_ID"] %>
  password: <%= ENV["CONNECT_PW"] %>
  host: 127.0.0.1
  # 127.0.0.1


# mysqlconnect Setting
CloudConnect: &mysqlsocket
  adapter: mysql2
  eencoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000  
  encoding: utf8
  username: <%= ENV["SOCKET_ID"] %>
  password: <%= ENV["SOCKET_PW"] %>
  socket: <%= ENV["SOCKET_URL"] %>


development:
  <<: *mysqlconnect
  database: development
  
## sqllit3 connect 
#  <<: *default
#  database: db/development.sqlite3
  

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or productio.
test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *mysqlsocket
  database: production
